name: Compose OSTree

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  compose:
    uses: Ultramarine-Kanopy/github-actions/.github/workflows/ostree.yml@main
    with:
      osVariant: '["9"]'
      unifiedCore: false
      gpgKeyID: 5D155AF6F77C8C9B
      upload: ${{ github.ref == 'refs/heads/main' }}
      runsOn: '["ubuntu-latest"]'
    secrets:
      repoIP: ${{ secrets.REPO_IP }}
      repoKnownHosts: ${{ secrets.REPO_KNOWN_HOSTS }}
      repoPrivateKey: ${{ secrets.REPO_PRIVATE_KEY }}
      signingKey: ${{ secrets.GPG_PRIVATE_KEY }}